### ISSUE TITLE
coolio

### ISSUE THREAD

**Issue by davidtlee** [stve/bower#6]
I've been having problems getting this to work. Everything's fine when I'm on dev, but when I push to heroku, I get this error on precompiling assets:

```
remote:        Sprockets::FileNotFound: couldn't find file 'coolio'
remote:        (in /tmp/build_f5c2acbf52130ab24efc0783594eed2d/vendor/bundle/ruby/2.1.0/gems/bower-0.0.2/spec/dummy/app/assets/javascripts/application.js:13)
```

I finally narrowed it down to this gem. Do you know what the `coolio.js` in `spec/dummy/app/assets/javascripts/application.js` is required for?

**Comment by stve** [comment]
that's really strange. `coolio.js` is a file used as part of the test suite: see https://github.com/stve/bower/blob/83321bd6e3af26d350c62039ea2efe804453446b/spec/features/bower_integration_spec.rb

I don't know why that would be required as part of your application though. I'll push a new version of the gem that excludes the test files and we'll see if that helps.

**Comment by stve** [comment]
give `0.0.3` a try

**Comment by davidtlee** [comment]
Seems to fix this problem. (it still didn't work, but that seems to be
problems on my end). Thanks!

On Thu, Mar 5, 2015 at 11:42 AM, Steve Agalloco <notifications@github.com>
wrote:

> give 0.0.3 a try
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/stve/bower/issues/6#issuecomment-77436354>.
>



-- 
David Lee
@davidtlee

**Comment by stve** [comment]
Sounds good, i'm going to close this out. Feel free to reopen if the issues persist. Thanks.
